### ISSUE TITLE
Basic authorisation microservice

### ISSUE THREAD

**Issue by Zwirek009** [Zwirek009/RSOProject#1]
Create basic REST service for validating users.  The service should be able to:
- process requests for logging in from frontend service (#2), response with token
- process requests from other microservice (#3 ) for validating if token is valid

Moreover the service should have a database (eg. SQLite) for securately storing user's credentials.

**Comment by mstar95** [comment]
Service:
- store users data in H2 in memory database.
- store distributed sessions in key-value Redis store
- process requests for logging in from api-gateway service (#2), response with session-cookie
- returns user data from session context
- there are no tokens for now, just simple distributed session
