### ISSUE TITLE
Authentication (pl. uwierzytelnienie)

### ISSUE THREAD

**Issue by Zwirek009** [Zwirek009/RSOProject#12]
Check, what authentication (pl. uwierzytelnienie) is and how it differs from authorisation (pl. authorization). Repair the terms used in our documentation.

**Comment by mstar95** [comment]
Authentication = login + password (who you are)

Authorization = permissions (what you are allowed to do)

**Comment by jedrka** [comment]
6.1 zmodyfikowane
