### ISSUE TITLE
CRUD in our BeerService

### ISSUE THREAD

**Issue by Zwirek009** [Zwirek009/RSOProject#14]
Is our BeerService a CRUD service? Is any other service a CRUD? If so, describe CRUD in context of the service/services.

**Comment by mstar95** [comment]
Technically, our auth-service is CRUD as well.

**Comment by mstar95** [comment]
Create a user is a CRUD operation, but POST/DELETE session is not a CRUD.

**Comment by mstar95** [comment]
"CRUD, on the other hand, is a mnemonic for the common operations you need for data in a database: Create Retrieve Update Delete. But it really doesn't get any deeper than that."

**Comment by Zwirek009** [comment]
Ok, so we shold specify CRUD operations in Auth-service description as well

**Comment by Lipsztyk** [comment]
CRUD is basically acronym created from 4 basic operations: **c**reate, **r**etrieve, **u**pdate and **d**elete. I updated documantation with lines mentioning, that Beer-service is implementing all this operations.
