### ISSUE TITLE
"Anonimizacja, solenie i hashowanie"

### ISSUE THREAD

**Issue by Zwirek009** [Zwirek009/RSOProject#17]
- [x] use for stored personal data
- [ ] describe in the documentation

**Comment by mstar95** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/18337052/40389854-ba013e1e-5e13-11e8-8f5b-1a7b0fa91751.png">
We use bCrypt function to encrypt passwords. 
https://sekurak.pl/kompendium-bezpieczenstwa-hasel-atak-i-obrona/
ad.3
